/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Musica;
import controller.MusicaDAO;
import model.Playlist;
import controller.PlaylistDAO;
import static view.TelaLogin.cpf;
import static view.TelaLogin.telaPrincipal;

/**
 * Classe para adicionar uma música a uma playlist.
 * @author Jhennifer
 */
public class AddMusicaNaPlaylist extends javax.swing.JFrame {

    /**
     * Creates new form AddMusicaNaPlaylist
     */
    public AddMusicaNaPlaylist() {
        initComponents();
        //Lendo as tabelas
        DefaultTableModel modeloMusica = (DefaultTableModel) this.jTableMusicas.getModel();
        this.jTableMusicas.setRowSorter(new TableRowSorter(modeloMusica));
        readJTableMusica();
        DefaultTableModel modeloPlaylist = (DefaultTableModel) this.jTablePlaylist.getModel();
        this.jTablePlaylist.setRowSorter(new TableRowSorter(modeloPlaylist));
        readJTablePlaylist();
    }

    /**
     * Método para ler e salvar dados na tabela referente as playlists
     */
    public void readJTablePlaylist() {
        DefaultTableModel modeloPlaylist = (DefaultTableModel) this.jTablePlaylist.getModel();
        PlaylistDAO playlistDAO = new PlaylistDAO();
        for (Playlist p : playlistDAO.buscarPlaylistCadastradas(cpf)) {
            modeloPlaylist.addRow(new Object[]{
                p.getNome(),
                p.getNumMusicas()
            });
        }
    }

    /**
     * Método para ler e salvar dados na tabela referente as musicas
     */
    public void readJTableMusica() {
        DefaultTableModel modeloMusica = (DefaultTableModel) this.jTableMusicas.getModel();
        MusicaDAO musicaDAO = new MusicaDAO();
        for (Musica m : musicaDAO.buscarMusicaSemFiltro()) {
            modeloMusica.addRow(new Object[]{
                m.getNome(),
                m.getArtista(),
                m.getGenero(),
                m.getAlbum(),
                m.getDuracao()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePlaylist = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMusicas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setResizable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_size_lado-removebg-preview.png"))); // NOI18N

        jTablePlaylist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Número de Músicas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePlaylist);

        jTableMusicas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Artista", "Genero", "Album", "Duracao"
            }
        ));
        jScrollPane2.setViewportView(jTableMusicas);

        jLabel3.setText("Selecione música e playlist dejadas:");

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addMusica();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Método para adicionar a musica na playlist
     */
    private void addMusica(){
        boolean sucesso = false;
        boolean atualizar = false;
        
        //quantidade de itens selecionados
        int rowIndex = jTablePlaylist.getSelectedRow();
        int rowIndex1 = jTableMusicas.getSelectedRow();
        
        //rowIndex = -1 -> nenhum item selecionado 
        if (rowIndex == -1) {
            JOptionPane.showMessageDialog(this, "Selecione a playlist!");
            return;
        }
        if (rowIndex1 == -1) {
            JOptionPane.showMessageDialog(this, "Selecione a musica!");
            return;
        }
        
        //conteudo dos itens selecionados
        String nomePlaylist = (String) this.jTablePlaylist.getModel().getValueAt(rowIndex, 0);
        String nomeMusica = (String) this.jTableMusicas.getModel().getValueAt(rowIndex1, 0);
        String artista = (String) this.jTableMusicas.getModel().getValueAt(rowIndex1, 1);

        PlaylistDAO playlistDAO = new PlaylistDAO();

        //adicionando a musica na playlist
        sucesso = playlistDAO.addMusicaEmPlaylist(nomeMusica, artista, nomePlaylist, cpf);
        if (sucesso) {
            JOptionPane.showMessageDialog(this, "Musica adicionada na playlist com sucesso");
            atualizar = playlistDAO.atualizaPlaylist(nomePlaylist, cpf);
            chamarTelaPrincipal();
            if(atualizar){
                JOptionPane.showMessageDialog(this, "Playlist atualizada");
            }
        } else {
            System.out.println("Tente novamente");
        }
    }
    
    /**
     * Método para exibir a classe TelaPrincipal 
     */
    private void chamarTelaPrincipal() {
        if (telaPrincipal == null) {
            telaPrincipal = new TelaPrincipal();
            telaPrincipal.setVisible(true);
        }
        this.setVisible(false);
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        chamarTelaPrincipal();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableMusicas;
    private javax.swing.JTable jTablePlaylist;
    // End of variables declaration//GEN-END:variables
}
