/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Musica;
import controller.MusicaDAO;
import static view.TelaLogin.telaPrincipal;

/**
 * Classe para analizar e criar nova musica no banco de dandos.
 * @author Jhennifer
 */
public class AddMusica extends javax.swing.JFrame {

    /**
     * Creates new form AddMusica
     */
    public AddMusica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelArtista = new javax.swing.JLabel();
        jTextFieldArtista = new javax.swing.JTextField();
        jLabelGenero = new javax.swing.JLabel();
        jTextFieldGenero = new javax.swing.JTextField();
        jLabelAlbum = new javax.swing.JLabel();
        jTextFieldAlbum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldDuracao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jButtonAdicionar = new javax.swing.JButton();
        jTextFieldNome = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setResizable(false);

        jLabelArtista.setText("Artista");

        jLabelGenero.setText("Genero");

        jLabelAlbum.setText("Album *");

        jLabel3.setText("Duração");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_size_lado-removebg-preview.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Adicionar Música:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel4.setText("* CAMPO NÃO OBRIGATÓRIO");

        jLabelNome.setText("Nome");

        jButtonAdicionar.setText("Adicionar");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(jButtonAdicionar))
                            .addComponent(jLabel3)
                            .addComponent(jLabelAlbum)
                            .addComponent(jLabelGenero)
                            .addComponent(jLabelArtista)
                            .addComponent(jLabelNome)
                            .addComponent(jTextFieldNome)
                            .addComponent(jTextFieldArtista)
                            .addComponent(jTextFieldGenero)
                            .addComponent(jTextFieldAlbum)
                            .addComponent(jTextFieldDuracao))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelNome)
                .addGap(10, 10, 10)
                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelArtista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelGenero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAlbum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdicionar)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        // TODO add your handling code here:
        verificaAdd();
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        chamarTelaPrincipal();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Método para exibir a classe TelaPrincipal 
     */
    private void chamarTelaPrincipal() {
        if (telaPrincipal == null) {
            telaPrincipal = new TelaPrincipal();
            telaPrincipal.setVisible(true);
        }
        this.setVisible(false);
    }
    
    /**
     * Método para exibir a classe AddMusica.
     */
    private void retornar() {
        AddMusica addMusica = new AddMusica();
        addMusica.setVisible(true);
        dispose();
    }

    /**
     * Método para salvar musica no banco.
     */
    private void addMusica(Musica musica) {
        MusicaDAO musicaDAO = new MusicaDAO();    
        if (this.album != null) {
            musicaDAO.inserirMusica(musica);
            VerMusica verMusica = new VerMusica();
            DefaultTableModel modelo = (DefaultTableModel) verMusica.getjTableMusicas().getModel();
            for (Musica m : musicaDAO.buscarMusicaSemFiltro()) {
                modelo.addRow(new Object[]{
                    m.getNome(),
                    m.getArtista(),
                    m.getGenero(),
                    m.getAlbum(),
                    m.getDuracao()
                });
            }
        } else {
            VerMusica verMusica = new VerMusica();
            DefaultTableModel modelo = (DefaultTableModel) verMusica.getjTableMusicas().getModel();
            for (Musica m : musicaDAO.buscarMusicaSemFiltro()) {
                modelo.addRow(new Object[]{
                    m.getNome(),
                    m.getArtista(),
                    m.getGenero(),
                    m.getDuracao()
                });
            }
        }
        JOptionPane.showMessageDialog(this, "Musica adicionada com sucesso!");
        chamarTelaPrincipal();
    }

    /**
     * Método para validar os dados da música.
     */
    private void verificaAdd() {
        nome = this.jTextFieldNome.getText();
        artista = this.jTextFieldArtista.getText();
        genero = this.jTextFieldGenero.getText();
        duracao = this.jTextFieldDuracao.getText();
        album = this.jTextFieldAlbum.getText();
        MusicaDAO musicaDAO = new MusicaDAO();
        boolean achou;
        if (nome.length() >0 && artista.length() > 0 && genero.length() > 0 && duracao.length() > 0) {
            achou = musicaDAO.buscarMusica(nome, artista);
            if (!achou) {
                if(album != null){
                    Musica musica = new Musica(nome, duracao, artista, genero, album);
                    addMusica(musica);
                }
                else{
                    Musica musica = new Musica(nome, duracao, artista, genero);
                    addMusica(musica);
                }                 
            } else {
                System.out.println("Nome de musica ja existente");
                retornar();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
            retornar();
        }
    }
    String nome;
    String artista;
    String genero;
    String duracao;
    String album;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAlbum;
    private javax.swing.JLabel jLabelArtista;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JTextField jTextFieldAlbum;
    private javax.swing.JTextField jTextFieldArtista;
    private javax.swing.JTextField jTextFieldDuracao;
    private javax.swing.JTextField jTextFieldGenero;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
