/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JDesktopPane;
import javax.swing.plaf.basic.BasicMenuBarUI;

/**
 * Classe que exibe as funções disponíveis para o usuario 
 * @author Jhennifer
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        //alterando a cor da barra de menu
        jMenuBarBarraDeMenu.setUI(new BasicMenuBarUI() {
            public void paint(Graphics g, JComponent c) {
                g.setColor(new Color(255, 130, 51));
            }
        });
        this.jDesktopPanePrincipal.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jDesktopPanePrincipal = new javax.swing.JDesktopPane(){
            ImageIcon icon = new ImageIcon("..\\Projeto\\src\\images\\logo_size_quadrado-removebg-preview.png");
            Image image = icon.getImage();
            Image nimage = image.getScaledInstance(165, 165, Image.SCALE_SMOOTH);
            @Override
            protected void paintComponent(Graphics g){
                super.paintComponents(g);
                g.drawImage(nimage, 90, 45, this);
            }
        };
        jMenuBarBarraDeMenu = new javax.swing.JMenuBar();
        jMenuMusicas = new javax.swing.JMenu();
        jMenuItemVerMusicas = new javax.swing.JMenuItem();
        jMenuItemAdicionarMusicas = new javax.swing.JMenuItem();
        jMenuItemExcluirMusicas = new javax.swing.JMenuItem();
        jMenuPlaylists = new javax.swing.JMenu();
        jMenuItemVerPlaylist = new javax.swing.JMenuItem();
        jMenuItemCriarPlaylists = new javax.swing.JMenuItem();
        jMenuItemAdicionarMusicaPlaylist = new javax.swing.JMenuItem();
        jMenuItemExcluirPlaylist = new javax.swing.JMenuItem();
        jMenuConfiguracoes = new javax.swing.JMenu();
        jMenuItemPerfil = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jDesktopPanePrincipal.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPanePrincipalLayout = new javax.swing.GroupLayout(jDesktopPanePrincipal);
        jDesktopPanePrincipal.setLayout(jDesktopPanePrincipalLayout);
        jDesktopPanePrincipalLayout.setHorizontalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );
        jDesktopPanePrincipalLayout.setVerticalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );

        jMenuBarBarraDeMenu.setBackground(new java.awt.Color(255, 120, 51));
        jMenuBarBarraDeMenu.setForeground(new java.awt.Color(255, 153, 0));

        jMenuMusicas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/music.png"))); // NOI18N
        jMenuMusicas.setText("Minhas Músicas");

        jMenuItemVerMusicas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bullet_go.png"))); // NOI18N
        jMenuItemVerMusicas.setText("Ver Musicas");
        jMenuItemVerMusicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerMusicasActionPerformed(evt);
            }
        });
        jMenuMusicas.add(jMenuItemVerMusicas);

        jMenuItemAdicionarMusicas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jMenuItemAdicionarMusicas.setText("Adicionar Musicas");
        jMenuItemAdicionarMusicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAdicionarMusicasActionPerformed(evt);
            }
        });
        jMenuMusicas.add(jMenuItemAdicionarMusicas);

        jMenuItemExcluirMusicas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jMenuItemExcluirMusicas.setText("Excluir Musicas");
        jMenuItemExcluirMusicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExcluirMusicasActionPerformed(evt);
            }
        });
        jMenuMusicas.add(jMenuItemExcluirMusicas);

        jMenuBarBarraDeMenu.add(jMenuMusicas);

        jMenuPlaylists.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cd.png"))); // NOI18N
        jMenuPlaylists.setText("Minhas Playlists");

        jMenuItemVerPlaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cd_go.png"))); // NOI18N
        jMenuItemVerPlaylist.setText("Ver Playlists");
        jMenuItemVerPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerPlaylistActionPerformed(evt);
            }
        });
        jMenuPlaylists.add(jMenuItemVerPlaylist);

        jMenuItemCriarPlaylists.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cd_add.png"))); // NOI18N
        jMenuItemCriarPlaylists.setText("Criar Nova Playlist");
        jMenuItemCriarPlaylists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCriarPlaylistsActionPerformed(evt);
            }
        });
        jMenuPlaylists.add(jMenuItemCriarPlaylists);

        jMenuItemAdicionarMusicaPlaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cd_edit.png"))); // NOI18N
        jMenuItemAdicionarMusicaPlaylist.setText("Adicionar Musica");
        jMenuItemAdicionarMusicaPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAdicionarMusicaPlaylistActionPerformed(evt);
            }
        });
        jMenuPlaylists.add(jMenuItemAdicionarMusicaPlaylist);

        jMenuItemExcluirPlaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cd_delete.png"))); // NOI18N
        jMenuItemExcluirPlaylist.setText("Excluir Playlists");
        jMenuItemExcluirPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExcluirPlaylistActionPerformed(evt);
            }
        });
        jMenuPlaylists.add(jMenuItemExcluirPlaylist);

        jMenuBarBarraDeMenu.add(jMenuPlaylists);

        jMenuConfiguracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cog.png"))); // NOI18N
        jMenuConfiguracoes.setText("Configurações");
        jMenuConfiguracoes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jMenuConfiguracoesItemStateChanged(evt);
            }
        });
        jMenuConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConfiguracoesActionPerformed(evt);
            }
        });

        jMenuItemPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jMenuItemPerfil.setText("Perfil");
        jMenuItemPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPerfilActionPerformed(evt);
            }
        });
        jMenuConfiguracoes.add(jMenuItemPerfil);

        jMenuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door_out.png"))); // NOI18N
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuConfiguracoes.add(jMenuItemSair);

        jMenuBarBarraDeMenu.add(jMenuConfiguracoes);

        setJMenuBar(jMenuBarBarraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuConfiguracoesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jMenuConfiguracoesItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuConfiguracoesItemStateChanged

    private void jMenuConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConfiguracoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuConfiguracoesActionPerformed

    private void jMenuItemVerPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerPlaylistActionPerformed
        // TODO add your handling code here:
        VerPlaylist verPlaylist = new VerPlaylist();
        verPlaylist.setVisible(true);
    }//GEN-LAST:event_jMenuItemVerPlaylistActionPerformed

    private void jMenuItemCriarPlaylistsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCriarPlaylistsActionPerformed
        // TODO add your handling code here:
        AddPlaylist addPlaylist = new AddPlaylist();
        addPlaylist.setVisible(true);
    }//GEN-LAST:event_jMenuItemCriarPlaylistsActionPerformed

    private void jMenuItemAdicionarMusicaPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAdicionarMusicaPlaylistActionPerformed
        // TODO add your handling code here:
        AddMusicaNaPlaylist addMusica = new AddMusicaNaPlaylist();
        addMusica.setVisible(true);
    }//GEN-LAST:event_jMenuItemAdicionarMusicaPlaylistActionPerformed

    private void jMenuItemExcluirMusicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExcluirMusicasActionPerformed
        // TODO add your handling code here:
        ExcluirMusica excluirMusica = new ExcluirMusica();
        excluirMusica.setVisible(true);
    }//GEN-LAST:event_jMenuItemExcluirMusicasActionPerformed

    private void jMenuItemPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPerfilActionPerformed
        // TODO add your handling code here:
        TelaPerfil telaPerfil = new TelaPerfil();
        telaPerfil.setVisible(true);
    }//GEN-LAST:event_jMenuItemPerfilActionPerformed

    private void jMenuItemVerMusicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerMusicasActionPerformed
        // TODO add your handling code here:
        VerMusica verMusica = new VerMusica();
        verMusica.setVisible(true);
    }//GEN-LAST:event_jMenuItemVerMusicasActionPerformed

    private void jMenuItemAdicionarMusicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAdicionarMusicasActionPerformed
        // TODO add your handling code here:
        AddMusica addMusica = new AddMusica();
        addMusica.setVisible(true);
    }//GEN-LAST:event_jMenuItemAdicionarMusicasActionPerformed

    private void jMenuItemExcluirPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExcluirPlaylistActionPerformed
        // TODO add your handling code here:
        ExcluirPlaylist excluirPlaylist = new ExcluirPlaylist();
        excluirPlaylist.setVisible(true);
    }//GEN-LAST:event_jMenuItemExcluirPlaylistActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        TelaLogin telaLogin = new TelaLogin();
        telaLogin.setVisible(true);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    public JDesktopPane getjDesktopPanePrincipal() {
        return jDesktopPanePrincipal;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPanePrincipal;
    private javax.swing.JMenuBar jMenuBarBarraDeMenu;
    private javax.swing.JMenu jMenuConfiguracoes;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAdicionarMusicaPlaylist;
    private javax.swing.JMenuItem jMenuItemAdicionarMusicas;
    private javax.swing.JMenuItem jMenuItemCriarPlaylists;
    private javax.swing.JMenuItem jMenuItemExcluirMusicas;
    private javax.swing.JMenuItem jMenuItemExcluirPlaylist;
    private javax.swing.JMenuItem jMenuItemPerfil;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemVerMusicas;
    private javax.swing.JMenuItem jMenuItemVerPlaylist;
    private javax.swing.JMenu jMenuMusicas;
    private javax.swing.JMenu jMenuPlaylists;
    // End of variables declaration//GEN-END:variables

}
